FROM node:12

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

RUN npm install -g http-server

WORKDIR /app/dist/angular-frontend

RUN ls -la

ENTRYPOINT ["http-server", "-c1", "-p", "80"]

